version: "3.9"

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"   # Maps container port 5000 to host port 5000
    volumes:
      - .:/app    # Mount the app directory for live updates during development
    restart: always   # Restart the container automatically on failure

